---
- name: Cisco IOS config
  connection: local
#  hosts: device_roles_access_switch, device_roles_wan_router
#  hosts: device_roles_access_switch, manufacturer_Cisco
  hosts: device_roles_wan_router
#  hosts: serointdsw33002,serointdsw33001,serointsr33001,serointsr33002 
#  hosts: serointsr33001 
  gather_facts: False

  roles:
    - role: Cisco-IOS_config
      tags: Cisco-IOS_config
