---

- name: Cisco Wired Campus Design
  hosts:  device_roles_wan_router
  gather_facts: false
  connection: local

  vars:
    cli:
      username: admin
      password: cisco

  tasks:
    - name: Global config settings
      ios_config:
        provider: "{{ cli }}"
        lines:
          - ip name-server 8.8.8.8
          - no ip http server
          - ip http secure-server

          - snmp-server community python1 RO
          - snmp-server community python2 RW

          - ntp server 87.81.181.2
          - ntp update-calendar

          - clock timezone PST -8
          - clock summer-time PDT recurring
          - service timestamps debug datetime msec localtime
          - service timestamps log datetime msec localtime

      register: print_output

    -  debug: var=print_output

