---
- name: Create VLAN Interfaces
  netbox.netbox.netbox_device_interface:
#    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
#    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
     netbox_url: http://192.168.122.29:8000
     netbox_token: 0123456789abcdef0123456789abcdef01234567
     data: "{{ interface }}"
     state: present    
  loop: "{{ interfaces }}"
  loop_control: 
    loop_var: interface
    label: "{{ interface['name']}}"
