---
- name: Create Aggregates within NetBox
  netbox.netbox.netbox_aggregate:
#    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
#    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
     netbox_url: http://192.168.1.153:8000
     netbox_token: 0123456789abcdef0123456789abcdef01234567
     data: "{{ aggregate }}"
     state: present
  loop: "{{ ipam_aggregates }}"
  loop_control: 
    loop_var: aggregate
    label: "{{ aggregate['prefix']}}"
